import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html>
            <body
                className={
                    inter.className +
                    "min-h-screen bg-background text-foreground"
                }
            >
                <ThemeProvider attribute="class">{children}</ThemeProvider>
            </body>
        </html>
    );
}
